//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.QuanLiTaiSan.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.QuanLiTaiSan.Common.Resources.ResourceVN", typeof(ResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lõi xảy ra vui lòng liên hệ MISA để được trợ giúp. .
        /// </summary>
        public static string Msg_Exception {
            get {
                return ResourceManager.GetString("Msg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dữ liệu thất bại.
        /// </summary>
        public static string Msg_Failed_Delete {
            get {
                return ResourceManager.GetString("Msg_Failed_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới dữ liệu thất bại.
        /// </summary>
        public static string Msg_Failed_Insert {
            get {
                return ResourceManager.GetString("Msg_Failed_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật dữ liệu thất bại.
        /// </summary>
        public static string Msg_Failed_Update {
            get {
                return ResourceManager.GetString("Msg_Failed_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dữ liệu thành công.
        /// </summary>
        public static string Msg_Success_Delete {
            get {
                return ResourceManager.GetString("Msg_Success_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới dữ liệu thành công.
        /// </summary>
        public static string Msg_Success_Insert {
            get {
                return ResourceManager.GetString("Msg_Success_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật dữ liệu thành công.
        /// </summary>
        public static string Msg_Success_Update {
            get {
                return ResourceManager.GetString("Msg_Success_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_{1}.
        /// </summary>
        public static string Procedure_Name {
            get {
                return ResourceManager.GetString("Procedure_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã tồn tại trong hệ thống.
        /// </summary>
        public static string Validate_Duplicate_Code {
            get {
                return ResourceManager.GetString("Validate_Duplicate_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được để trống.
        /// </summary>
        public static string Validate_Empty_InputField {
            get {
                return ResourceManager.GetString("Validate_Empty_InputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị {0} mà bạn lựa chọn không tồn tại trong hệ thống .
        /// </summary>
        public static string Validate_Exist_Selection {
            get {
                return ResourceManager.GetString("Validate_Exist_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được phép nhập quá {1} kí tự..
        /// </summary>
        public static string Validate_MaxLength {
            get {
                return ResourceManager.GetString("Validate_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉ lệ hao mòn phải bằng 1 chia số năm sử dụng.
        /// </summary>
        public static string Validate_Valid_DepreciationRate {
            get {
                return ResourceManager.GetString("Validate_Valid_DepreciationRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị hao mòn năm phải bằng nguyên giá nhân tỉ lệ hao mòn.
        /// </summary>
        public static string Validate_Valid_DepreciationValue {
            get {
                return ResourceManager.GetString("Validate_Valid_DepreciationValue", resourceCulture);
            }
        }
    }
}
